In [33]:
import pandas as pd
import numpy as np
from difflib import SequenceMatcher
import itertools
import re
import plotly.express as px
pd.options.mode.chained_assignment = None  # default='warn'

In [10]:
columns = ['ticket_no','title','type','configuration','level']

data = [
  [1, "Server: ctil-sqlssis02.ctil.local Disk Free Space: F:", "Space Issue","ctil-sqlssis02.ctil.local","parent"], 
  [2, "Server: UKCPPBNODE4.rws.com Disk Free Space: G:", "Space Issue","cUKCPPBNODE4.rws.com","parent"], 
  [3, "PagerDuty: Server:  AlwaysOn replica is not in the PRIMARY or SECONDARY role - custom", "","LDSQLMID01.rimes.dir","child"], 
  [4, "PagerDuty: Server:  AlwaysOn replica is not in the PRIMARY or SECONDARY role - custom", "HA-DR","UKCPPBNODE4.rws.com","parent"], 
  [5, "PagerDuty: Server:  AlwaysOn replica is not in the PRIMARY or SECONDARY role - custom", "HA-DR","ctil-sqlssis01.ctil.local","parent"], 
  [6, "RCA: BSS-DES-SQL07\BSSERP  Availability Group [AlwaysOn replica is not in the PRIMARY or SECONDARY]", "HA-DR","BSS-DES-SQL07\BSSERP","parent"], 
  [7, "PagerDuty: Server:  AlwaysOn replica is not in the PRIMARY or SECONDARY role - custom", "HA-DR","","child"], 
  [8, "PagerDuty: Server:  AlwaysOn replica is not in the PRIMARY or SECONDARY role - custom", "HA-DR","ctil-sqlssis02.ctil.local","parent"], 
  [9, "PagerDuty: Server: BSS-DEP-SQL07\BSSERP AlwaysOn replica is not in the PRIMARY or SECONDARY role - custom", "HA-DR","","parent"], 
  [10, "Server: LDSQLMID01.rimes.dir Disk Free Space: F:", "Space Issue","LDSQLMID01.rimes.dir","parent"],   
  [11, "Server: TGSQLCLUST02.trakglobal.local Disk Free Space: Cluster Disk 16_K:", "Space Issue","TGSQLCLUST02.trakglobal.local","parent"], 
  [12, "Server: SOUSQ01L.ITSLAW.CO.UK Disk Free Space: G:", "Space Issue","SOUSQ01L.ITSLAW.CO.UK","parent"], 
  [13, "RCA - AlwaysOn replica is not in the PRIMARY or SECONDARY role on  PUBLICSQLF", "Service Failure","","parent"], 
  [14, "PagerDuty: Server:  AlwaysOn replica is not in the PRIMARY or SECONDARY role - custom", "Service Failure","","parent"], 
  [15, "PagerDuty: Server:  AlwaysOn replica is not in the PRIMARY or SECONDARY role - custom", "HA-DR","","child"], 
  [16, "PagerDuty: Server: LDSQLMID01.rimes.dir AlwaysOn replica is not in the PRIMARY or SECONDARY role - custom", "","LDSQLMID01.rimes.dir","parent"], 
  [17, "PagerDuty: Server:  AlwaysOn replica is not in the PRIMARY or SECONDARY role - custom", "HA-DR","","parent"], 
  [18, "PagerDuty: Server: UKCPPBNODE4.rws.com AlwaysOn replica is not in the PRIMARY or SECONDARY role - custom", "HA-DR","UKCPPBNODE4.rws.com ","parent"], 
]

In [12]:
df = pd.DataFrame(data=data, columns=columns)
df.set_index('ticket_no',inplace=True)
df.title = df.title.str.lower()
df.head()

,title,type,configuration,level
ticket_no,,,,
1,server: ctil-sqlssis02.ctil.local disk free sp...,Space Issue,ctil-sqlssis02.ctil.local,parent
2,server: ukcppbnode4.rws.com disk free space: g:,Space Issue,cUKCPPBNODE4.rws.com,parent
3,pagerduty: server: alwayson replica is not in...,,LDSQLMID01.rimes.dir,child
4,pagerduty: server: alwayson replica is not in...,HA-DR,UKCPPBNODE4.rws.com,parent
5,pagerduty: server: alwayson replica is not in...,HA-DR,ctil-sqlssis01.ctil.local,parent

In [13]:
# DataFrame of only parent tickets
df2 = df[df['level']=='parent']

In [14]:
# group by titles and type to see if any are ambiguous
grouped_df = df2.groupby(['title','type'],as_index=False).count()
grouped_df.rename(columns={'level':'count'},inplace=True)
grouped_df

,title,type,configuration,count
0,pagerduty: server: alwayson replica is not in...,HA-DR,4,4
1,pagerduty: server: alwayson replica is not in...,Service Failure,1,1
2,pagerduty: server: bss-dep-sql07\bsserp always...,HA-DR,1,1
3,pagerduty: server: ldsqlmid01.rimes.dir always...,,1,1
4,pagerduty: server: ukcppbnode4.rws.com alwayso...,HA-DR,1,1
5,rca - alwayson replica is not in the primary o...,Service Failure,1,1
6,rca: bss-des-sql07\bsserp availability group ...,HA-DR,1,1
7,server: ctil-sqlssis02.ctil.local disk free sp...,Space Issue,1,1
8,server: ldsqlmid01.rimes.dir disk free space: f:,Space Issue,1,1
9,server: sousq01l.itslaw.co.uk disk free space: g:,Space Issue,1,1
10,server: tgsqlclust02.trakglobal.local disk fre...,Space Issue,1,1
11,server: ukcppbnode4.rws.com disk free space: g:,Space Issue,1,1

In [15]:
# Show that some titles have multiple ticket types currently
grouped_grouped_df = grouped_df.groupby('title').count()
count_df = grouped_grouped_df[grouped_grouped_df['type']>1]
count_df[['count']]

                                                    count
title
pagerduty: server:  alwayson replica is not in ...      2

In [19]:
# Start pre-processing to strip titles and reduce as something to more easily group
# Check if we need .  and \ and any others
df2['configuration_stripped'] = df2['configuration'].str.split(pat=".").str[0]

def f(title, replace1, replace2):
    x = title.replace(replace1, '').replace(replace2, '')
    return x

df2['title_stripped'] = df2.apply(lambda x: f(x['title'], x['configuration'], x['configuration_stripped']),axis=1)

df2['title_stripped'] = df2['title_stripped'] \
.apply(lambda x: x.replace('server: ','')) \
.apply(lambda x: x.replace('pagerduty: ','')) \
.apply(lambda x: x.replace('rca: ','')) \
.apply(lambda x: x.replace('rca - ','')) \
.apply(lambda x: x.strip())
df2['title_stripped'] = df2['title_stripped'].str.split(pat=".local").str[-1]
df2['title_stripped'] = df2['title_stripped'].str.split(pat=".com").str[-1]
df2['title_stripped'] = df2['title_stripped'].str.split(pat=".co.uk").str[-1]
df2['title_stripped'] = df2['title_stripped'].str.strip()
with pd.option_context('display.max_colwidth', None):
  display(df2['title_stripped'])

ticket_no
1                                                                                disk free space: f:
2                                                                                disk free space: g:
4                                  alwayson replica is not in the primary or secondary role - custom
5                                  alwayson replica is not in the primary or secondary role - custom
6     bss-des-sql07\bsserp  availability group [alwayson replica is not in the primary or secondary]
8                                  alwayson replica is not in the primary or secondary role - custom
9             bss-dep-sql07\bsserp alwayson replica is not in the primary or secondary role - custom
10                                                          ldsqlmid01.rimes.dir disk free space: f:
11                                                               disk free space: cluster disk 16_k:
12                                                                               disk free space: g:
13                           alwayson replica is not in the primary or secondary role on  publicsqlf
14                                 alwayson replica is not in the primary or secondary role - custom
16            ldsqlmid01.rimes.dir alwayson replica is not in the primary or secondary role - custom
17                                 alwayson replica is not in the primary or secondary role - custom
18                                 alwayson replica is not in the primary or secondary role - custom
Name: title_stripped, dtype: object

In [20]:
# group by titles and type to see if any are ambiguous
grouped_df = df2.groupby(['title_stripped','type'],as_index=False).count()
grouped_df.rename(columns={'level':'count'})
with pd.option_context('display.max_colwidth', None):
  display(grouped_df)

,title_stripped,type,title,configuration,level,configuration_stripped
0,alwayson replica is not in the primary or secondary role - custom,HA-DR,5,5,5,5
1,alwayson replica is not in the primary or secondary role - custom,Service Failure,1,1,1,1
2,alwayson replica is not in the primary or secondary role on publicsqlf,Service Failure,1,1,1,1
3,bss-dep-sql07\bsserp alwayson replica is not in the primary or secondary role - custom,HA-DR,1,1,1,1
4,bss-des-sql07\bsserp availability group [alwayson replica is not in the primary or secondary],HA-DR,1,1,1,1
5,disk free space: cluster disk 16_k:,Space Issue,1,1,1,1
6,disk free space: f:,Space Issue,1,1,1,1
7,disk free space: g:,Space Issue,2,2,2,2
8,ldsqlmid01.rimes.dir alwayson replica is not in the primary or secondary role - custom,,1,1,1,1
9,ldsqlmid01.rimes.dir disk free space: f:,Space Issue,1,1,1,1

In [21]:
# Same verification as above
grouped_grouped_df = grouped_df.groupby('title_stripped').count()
count_df = grouped_grouped_df[grouped_grouped_df['type']>1]
count_df = count_df[['type']]
count_df.rename(columns={'type':'count'}, inplace='True')
count_df

                                                    count
title_stripped
alwayson replica is not in the primary or secon...      2

In [37]:
# Heatmap to show
# group cols - we want a linkage between related stripped titles.
def similar(a, b):
    return SequenceMatcher(None, a, b).ratio()


def correlation_matrix(titles):
    df_list = []
    for i in titles:
        row = [i]
        for j in titles:
            row.append(similar(j,i))
        df_list.append(row)

    df_x = pd.DataFrame(df_list, columns = ['title'] + titles)
    df_x.set_index('title', inplace=True)

    fig = px.imshow(df_x)
    fig.update_xaxes(showticklabels=False).update_yaxes(showticklabels=False)
    # fig.show()
    return df_x

def group_similar(df):
    s = np.where(df.gt(0.8,0), [i for i in df.columns], '')
    similar_lists = pd.Series([list(filter(None, i)) for i in s])
    
    groups = []
    for i in similar_lists:
        groups.append(list(set(i)))
    groups.sort()
    groups = list(groups for groups,_ in itertools.groupby(groups))
    
    remove_ = [group for group in groups if len(group) == 1]
    for i in remove_:
        groups.remove(i)

    # https://stackoverflow.com/questions/38862657/find-value-greater-than-level-python-pandas
    def long_substr(data):
        substrs = lambda x: {x[i:i+j] for i in range(len(x)) for j in range(len(x) - i + 1)}
        s = substrs(data[0])
        for val in data[1:]:
            s.intersection_update(substrs(val))
        return max(s, key=len)

    stripped = []
    for i in groups:
        stripped.append(long_substr(i))
    stripped = [i.strip() for i in stripped]
    stripped = list(set(stripped))
    
    # Add removed titles back in
    removed = [i[0] for i in remove_]
    titles_stripped = [*removed, *stripped]
    titles_stripped = list(set(titles_stripped))    
    return titles_stripped


# Add main_function
# Add levels to iterate through!
def full(titles, levels=1):
    features = [len(titles)]
    counter = 0 
    titles_stripped = titles
    while counter < levels:
        df = correlation_matrix(titles_stripped)
        titles_stripped = group_similar(df)
        features.append(len(titles_stripped))
        counter += 1
        print()
    return titles_stripped, features

In [39]:
titles_col = df2[['title_stripped']].drop_duplicates()
titles = list(titles_col['title_stripped'])
titles_stripped, features = full(titles,3)
titles_stripped

['bss-des-sql07\\bsserp  availability group [alwayson replica is not in the primary or secondary]',
 'disk free space: cluster disk 16_k:',
 'disk free space:',
 'alwayson replica is not in the primary or secondary role',
 'ldsqlmid01.rimes.dir disk free space: f:']

In [40]:
def ratios(title):
    df3 = df2[df2['title_stripped'].str.contains(title)][['type','title']].groupby('type').count()
    df3.rename(columns={'title':'count'},inplace=True)
    return df3

titles_stripped = [i.strip() for i in titles_stripped]

titles_stripped = list(set(titles_stripped))

for i in titles_stripped:
    print(i)
    df4 = ratios(i)
    print(df4['count'].max())
    print(df4['count'].sum())
    print()

bss-des-sql07\bsserp  availability group [alwayson replica is not in the primary or secondary]
nan
0

disk free space: cluster disk 16_k:
1
1

disk free space:
5
5

alwayson replica is not in the primary or secondary role
6
9

ldsqlmid01.rimes.dir disk free space: f:
1
1

In [51]:
# if len(list_2) > 1 (e.g. [alwayson, alwayson replica,...]) then this will only grab the 1st element of the list for new title
# hopefully captured already but who knows...
list_1 = []
for i in df2['title_stripped']:
    list_2 = []
    for j in titles_stripped:
        if j in i:
            list_2.append(j)
        else: 
            pass
    print(list_2)
    if list_2:
        list_1.append(list_2[0])
    else:
        list_1.append(i)
df2['title_stripped_2'] = list_1
df2.head()

['disk free space:']
['disk free space:']
['alwayson replica is not in the primary or secondary role']
['alwayson replica is not in the primary or secondary role']
['bss-des-sql07\\bsserp  availability group [alwayson replica is not in the primary or secondary]']
['alwayson replica is not in the primary or secondary role']
['alwayson replica is not in the primary or secondary role']
['disk free space:', 'ldsqlmid01.rimes.dir disk free space: f:']
['disk free space: cluster disk 16_k:', 'disk free space:']
['disk free space:']
['alwayson replica is not in the primary or secondary role']
['alwayson replica is not in the primary or secondary role']
['alwayson replica is not in the primary or secondary role']
['alwayson replica is not in the primary or secondary role']
['alwayson replica is not in the primary or secondary role']

,title,type,configuration,level,configuration_stripped,title_stripped,title_stripped_2
ticket_no,,,,,,,
1,server: ctil-sqlssis02.ctil.local disk free sp...,Space Issue,ctil-sqlssis02.ctil.local,parent,ctil-sqlssis02,disk free space: f:,disk free space:
2,server: ukcppbnode4.rws.com disk free space: g:,Space Issue,cUKCPPBNODE4.rws.com,parent,cUKCPPBNODE4,disk free space: g:,disk free space:
4,pagerduty: server: alwayson replica is not in...,HA-DR,UKCPPBNODE4.rws.com,parent,UKCPPBNODE4,alwayson replica is not in the primary or seco...,alwayson replica is not in the primary or seco...
5,pagerduty: server: alwayson replica is not in...,HA-DR,ctil-sqlssis01.ctil.local,parent,ctil-sqlssis01,alwayson replica is not in the primary or seco...,alwayson replica is not in the primary or seco...
6,rca: bss-des-sql07\bsserp availability group ...,HA-DR,BSS-DES-SQL07\BSSERP,parent,BSS-DES-SQL07\BSSERP,bss-des-sql07\bsserp availability group [alwa...,bss-des-sql07\bsserp availability group [alwa...

#Group similar columns in df

In [54]:
# group by titles and type to see if any are ambiguous
# this will probably introduce more ambiguity in predictions...
# potentially limit the use cases
grouped_df = df2.groupby(['title_stripped_2','type'],as_index=False).count()
grouped_df.rename(columns={'level':'count'})
with pd.option_context('display.max_colwidth', None):
  display(grouped_df)
# Same verification as above
grouped_grouped_df = grouped_df.groupby('title_stripped_2').count()
count_df = grouped_grouped_df[grouped_grouped_df['type']>1]
count_df = count_df[['type']]
count_df.rename(columns={'type':'count'}, inplace='True')
count_df

,title_stripped_2,type,title,configuration,level,configuration_stripped,title_stripped
0,alwayson replica is not in the primary or secondary role,,1,1,1,1,1
1,alwayson replica is not in the primary or secondary role,HA-DR,6,6,6,6,6
2,alwayson replica is not in the primary or secondary role,Service Failure,2,2,2,2,2
3,bss-des-sql07\bsserp availability group [alwayson replica is not in the primary or secondary],HA-DR,1,1,1,1,1
4,disk free space:,Space Issue,4,4,4,4,4
5,disk free space: cluster disk 16_k:,Space Issue,1,1,1,1,1

                                                    count
title_stripped_2
alwayson replica is not in the primary or secon...      3